resolver: lts-21.25

packages:
- '.'

extra-deps:
- git: git@github.com:adamwalker/sylvan-haskell
  commit: 53a2f5ea9d3c67a95f132f1de05bf7e82f5d5fb8

allow-newer: true

extra-lib-dirs:
- /usr/local/lib
